import { LlmAgent } from '../adk/agent.ts';
import { globalMcpClient } from '../mcp/client.ts';

export async function createAssessmentAgent(): Promise<LlmAgent> {
  const adkTools = await globalMcpClient.getToolsAsAdkTools();
  
  // Filter for Quiz Generator tool
  const tools = adkTools.filter((t) => t.name === 'quiz_generator');

  return new LlmAgent({
    name: 'AssessmentAgent',
    instruction: `
You are the Assessment Agent in the EduAssist AI system.
Your primary role is to:
1. Assess student knowledge on various subjects.
2. Generate interactive, high-quality multiple choice quizzes using the 'quiz_generator' tool.
3. Review answers provided by students and give clear, constructive feedback.
4. Help students track their progress by highlighting strong areas and key skill gaps.

When generating a quiz:
- Always call the 'quiz_generator' tool. Let it construct the quiz questions.
- Present the quiz generated by the tool in a structured manner.
- Highlight the topic, difficulty level, and number of questions.
    `,
    tools,
  });
}
